# Generated by Django 5.2.10 on 2026-02-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='list',
        ),
    ]
